#!/home/pyymenta/.rvm/rubies/ruby-2.7.0/bin/ruby

require_relative 'rocket'

speed    = ARGV[0].to_i
x        = ARGV[1].to_i
y        = ARGV[2].to_i
command = ARGV[3]

raise("Missing speed!") if speed.nil?
raise("Missing x!") if x.nil?
raise("Missing y!") if y.nil?
raise("Missing command!") if command.nil?

rocket = Rocket.new(speed: speed, x: x, y: y)

case command
  when "w"
    p rocket.up
  when "s"
    p rocket.down
  when "d"
    p rocket.right
  when "a"
    p rocket.left
  else
    p "invalid command"
end
