#!/home/pyymenta/.rvm/rubies/ruby-2.7.0/bin/ruby

require_relative 'rocket'

def run_cli(rocket, command)
  raise("Missing command!") if command.nil?

  case command
    when "w"
      p rocket.up
    when "s"
      p rocket.down
    when "d"
      p rocket.right
    when "a"
      p rocket.left
    when "q"
      p "Bye!"
    else
      p "invalid command"
  end
end

rocket = Rocket.new

loop do
  command = gets.chomp

  run_cli(rocket, command)

  break if command == "q" || rocket.y > 250
end
